### ISSUE TITLE
discord link invalid

### ISSUE THREAD

**Issue by adarshxs** [lucidrains/multimodal-dit-pytorch#1]
hey I tried to join the server but I am unable to. I think the links invalid: https://discord.gg/x6FuzQPQXY

**Comment by shxrif** [comment]
@lucidrains

**Comment by lucidrains** [comment]
@Ayaan-Sharif oh, my bad, want to try again?

**Comment by adarshxs** [comment]
yay works! thanks

**Comment by idevede** [comment]
Invalid again 😢. Could you send me the link to "idevede@gmail.com"

**Comment by asapsav** [comment]
@idevede @adarshxs  hi guys - what happened to the discord server? if its still alive - could you add me? holins12@gmail.com

**Comment by shxrif** [comment]
@lucidrains please let me in 🥹

**Comment by shxrif** [comment]
@lucidrains i saw u mentiond that u put off the DC whyman lots of people were there
